function [glcm] = glcm_generate(image, RoI, direction, levels)
%GLCM_GENERATE Creates a GLCM from a given grayscale image matrix, a
%direction vector, and a given RoI.
%   This GLCM is generated by taking as input an image and a binary mask of
%   the RoI. Only the pixels contained in the RoI will be accounted for the
%   GLCM. The matrix calculation is canonical.
%   Just one thing: for debuging causes, the levels arg dictates the size
%   of the glcm. It MUST be removed because we always have a 256x256 mat.

    [lines columns] = size(image);
    glcm = zeros(levels, levels);
    
    for i = 1:lines
        for j = 1:columns
            % direction follows the format: (lines of displacement,
            % columns of displacement), so [0 1] means 0 degree, [-1 0]
            % means 90 degrees and so on.
            x = i + direction(1);
            y = j + direction(2);
            
            if (x >= 1 && x <= lines && y >= 1 && y <= columns)
                % If both the point and the displacement are in the RoI, 
                % then it's a valid point for GLCM calculation.
                if (RoI(i, j) && RoI(x, y))
                    glcm(1 + image(i, j), 1 + image(x, y)) = glcm(1 + image(i, j), 1 + image(x, y)) + 1;
                end
            end
        end
    end
    
end

